### ISSUE TITLE
randomly choosing validators

### ISSUE THREAD

**Issue by youngdahlm** [ed-is-on/grantblock#5]
When a grantee generates a new action request, there should be a mechanism in the smart contract to get the participant registry of grantees from that program, select a set number of them randomly (2, 3, or 4?) then slot them into the "validator" slot for that action request and send them the action request for validation.

**Comment by bryaNgwa** [comment]
@youngdahlm The addValidatingGrantees function selected the grantee who created the action request as a validator

![image](https://user-images.githubusercontent.com/20949833/43800049-455d9068-9a5d-11e8-8123-2639b3528075.png)

**Comment by youngdahlm** [comment]
Hey Bryan, can you check to make sure that the code in your logic file looks like this?

`//remove the owner from contention for validation
    var identifier = currentReq.owner.getIdentifier();
    identifier = identifier.substring((identifier.indexOf("#")+1), (identifier.indexOf("}")));

    var index = granteeList.indexOf(identifier);
    if (index > -1) {
      granteeList.splice(index, 1);
    }
`
I'll also run some more tests on the develop branch to make sure this works for all ID combinations.

**Comment by youngdahlm** [comment]
Whoops, it didn't recognize the entire thing as code

`//remove the owner from contention for validation
    var identifier = currentReq.owner.getIdentifier();
    identifier = identifier.substring((identifier.indexOf("#")+1), (identifier.indexOf("}")));

    var index = granteeList.indexOf(identifier);
    if (index > -1) {
      granteeList.splice(index, 1);
    }`

**Comment by youngdahlm** [comment]
Found the issue was a difference in the code version we were running, and closing out the issue.
